[project]
name = "dobot-mujoco-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mujoco>=3.3.7",
    "numpy<2",
    "sb3-contrib>=2.7.0",
    "stable-baselines3>=2.7.0",
]
